Global:
  debug: false
  use_gpu: true
  epoch_num: 300
  log_smooth_window: 20
  print_batch_step: 50
  save_model_dir: ./output/kie_4/
  save_epoch_step: 50
  eval_batch_step:
  - 0
  - 80
  load_static_weights: false
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  class_path: /paddle/data/PaddleOCR/train_data/wildreceipt/class_list.txt
  infer_img: /paddle/data/PaddleOCR/train_data/wildreceipt/1.txt
  save_res_path: ./output/sdmgr_kie/predicts_kie.txt
  img_scale:
  - 1024
  - 512
  distributed: true
Architecture:
  model_type: kie
  algorithm: SDMGR
  Transform: null
  Backbone:
    name: Kie_backbone
  Head:
    name: SDMGRHead
Loss:
  name: SDMGRLoss
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup: 1
  regularizer:
    name: L2
    factor: 0.0005
PostProcess:
  name: None
Metric:
  name: KIEMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/data/PaddleOCR/train_data/wildreceipt/
    label_file_list:
    - /paddle/data/PaddleOCR/train_data/wildreceipt/wildreceipt_train.txt
    ratio_list:
    - 1.0
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - KieLabelEncode:
        character_dict_path: /paddle/data/PaddleOCR/train_data/wildreceipt/dict.txt
    - KieResize: null
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - relations
        - texts
        - points
        - labels
        - tag
        - shape
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 4
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /paddle/data/PaddleOCR/train_data/wildreceipt
    label_file_list:
    - /paddle/data/PaddleOCR/train_data/wildreceipt/wildreceipt_test.txt
    transforms:
    - DecodeImage:
        img_mode: RGB
        channel_first: false
    - NormalizeImage:
        scale: 1
        mean:
        - 123.675
        - 116.28
        - 103.53
        std:
        - 58.395
        - 57.12
        - 57.375
        order: hwc
    - KieLabelEncode:
        character_dict_path: /paddle/data/PaddleOCR/train_data/wildreceipt/dict.txt
    - KieResize: null
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - relations
        - texts
        - points
        - labels
        - tag
        - ori_image
        - ori_boxes
        - shape
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 4
